export const ErrorCodes = {
  // Auth
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  CODE_ALREDY_SENT: 'CODE_ALREDY_SENT',
  CODE_EXPIRED: 'CODE_EXPIRED',
  INVALID_CODE: 'INVALID_CODE',

  // Collection
  COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',
  COLLECTION_IS_PRIVATE: 'COLLECTION_IS_PRIVATE',
  COLLECTIONS_LIMIT_REACHED: 'LIMIT_OF_COLLECTIONS_REACHED',

  // File
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILES_LIMIT_REACHED: 'LIMIT_OF_FILES_REACHED',
  TOO_MANY_FILES: 'TOO_MANY_FILES',
  FILE_ALREADY_FAVORITED: 'FILE_ALREADY_FAVORITED',
  INVALID_GIPHY_IDS: 'INVALID_GIPHY_IDS',
};
